/*
 * @Author: Iversu
 * @LastEditors: daweslinyu
 * @LastEditTime: 2024-02-20 11:13:33
 * @Description:
 *
 *
 * The following is the Chinese and English copyright notice, encoded as UTF-8.
 * 以下是中文及英文版权同步声明，编码为UTF-8。
 * Copyright has legal effects and violations will be prosecuted.
 * 版权具有法律效力，违反必究。
 *
 * Copyright ©2021-2025 Sparkle Silicon Technology Corp., Ltd. All Rights Reserved.
 * 版权所有 ©2021-2025龙晶石半导体科技（苏州）有限公司
 */
#ifndef KERNEL_TRIM_H
#define KERNEL_TRIM_H
#include "AE_GLOBAL.H" //全局变量
#include "AE_REG.H"    //寄存器
#include "AE_CONFIG.H"
#include "AE_PRINTF.H"
#include "AE_MALLOC.H"
#endif