/*
 * @Author: Maple
 * @LastEditors: daweslinyu 
 * @LastEditTime: 2024-07-19 10:36:32
 * @Description:
 *
 *
 * The following is the Chinese and English copyright notice, encoded as UTF-8.
 * 以下是中文及英文版权同步声明，编码为UTF-8。
 * Copyright has legal effects and violations will be prosecuted.
 * 版权具有法律效力，违反必究。
 *
 * Copyright ©2021-2023 Sparkle Silicon Technology Corp., Ltd. All Rights Reserved.
 * 版权所有 ©2021-2023龙晶石半导体科技（苏州）有限公司
 */
#ifndef _TEST_INTC_H_
#define _TEST_INTC_H_
#include "AE_GLOBAL.H"
#include "AE_REG.H"
#include "AE_CONFIG.H"
#include "KERNEL_MEMORY.H"
#include "AE_DEBUGGER.H"
#include "KERNEL_INTC.H"
#include "KERNEL_MAIN.H"
#include "KERNEL_I2C.H"
#include "TEST_CONFIG.H"
extern uint32_t *Lpc_Mon_Ptr;

#endif