/*
 * @Author: Maple
 * @LastEditors: daweslinyu
 * @LastEditTime: 2024-06-12 14:47:37
 * @Description:
 *
 *
 * The following is the Chinese and English copyright notice, encoded as UTF-8.
 * 以下是中文及英文版权同步声明，编码为UTF-8。
 * Copyright has legal effects and violations will be prosecuted.
 * 版权具有法律效力，违反必究。
 *
 * Copyright ©2021-2025 Sparkle Silicon Technology Corp., Ltd. All Rights Reserved.
 * 版权所有 ©2021-2025龙晶石半导体科技（苏州）有限公司
 */
#ifndef TEST_SOC_FUNC_H
#define TEST_SOC_FUNC_H
#include "AE_GLOBAL.H"
#include "AE_REG.H"
#include "AE_CONFIG.H"
#include "TEST_CONFIG.H"
#include "KERNEL_INCLUDE.H"
// #include "HARDWARE_INCLUDE.H"
__BEGIN_DECLS
void Module_init();
__END_DECLS
#endif
