/*
 * @Author: Maple
 * @LastEditors: daweslinyu 
 * @LastEditTime: 2024-07-19 10:36:02
 * @Description:
 *
 *
 * The following is the Chinese and English copyright notice, encoded as UTF-8.
 * 以下是中文及英文版权同步声明，编码为UTF-8。
 * Copyright has legal effects and violations will be prosecuted.
 * 版权具有法律效力，违反必究。
 *
 * Copyright ©2021-2023 Sparkle Silicon Technology Corp., Ltd. All Rights Reserved.
 * 版权所有 ©2021-2023龙晶石半导体科技（苏州）有限公司
 */
#ifndef AUTO_TEST_H
#define AUTO_TEST_H
#include "AE_REG.H"
#include "AE_CONFIG.H"
#include "KERNEL_INCLUDE.H"
#include "TEST_CONFIG.H"
extern void AUTO_TEST_PORT(BYTE  channel);
#endif