/*
 * @Author: Iversu
 * @LastEditors: Iversu
 * @LastEditTime: 2023-04-02 21:20:23
 * @Description:
 *
 *
 * The following is the Chinese and English copyright notice, encoded as UTF-8.
 * 以下是中文及英文版权同步声明，编码为UTF-8。
 * Copyright has legal effects and violations will be prosecuted.
 * 版权具有法律效力，违反必究。
 *
 * Copyright ©2021-2023 Sparkle Silicon Technology Corp., Ltd. All Rights Reserved.
 * 版权所有 ©2021-2023龙晶石半导体科技（苏州）有限公司
 */
#ifndef CUSTOM_INCLUDE_H
#define CUSTOM_INCLUDE_H
//-----------------------------------------------------------------------------
#include "AE_GLOBAL.H"//全局变量
//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
#include "CUSTOM_MAIN.H"
#include "CUSTOM_MEMORY.H"
#include "CUSTOM_GPIO.H"
#include "CUSTOM_PMC1.H"
#include "CUSTOM_KBC6064.H"
#include "CUSTOM_LED.H"
#include "CUSTOM_PMC2.H"
#include "CUSTOM_POWER.H"
#include "CUSTOM_BATTERY.H"
#include "CUSTOM_TEMPERATURE.H"
#include "CUSTOM_PMC3.H"
#include "CUSTOM_PMC4.H"
#include "CUSTOM_PMC5.H"
#include "CUSTOM_FAN.H"
#include "CUSTOM_EVENT.H"
#include "CUSTOM_SCANTABS.H"
#include "CUSTOM_INIT.H"
#include "CUSTOM_ANX7447_PORT.H"
//-----------------------------------------------------------------------------
#endif
